### ISSUE TITLE
Fix empty stdout field of g++ compiler

### ISSUE THREAD

**Issue by virtustron** [ITA-Dnipro/CompilerWebApp#14]
There is no data in stdout field of g++ compiler both in case of successful execution and compilation error

https://github.com/ITA-Dnipro/CompilerWebApp/blob/212eeba30b3f489ecd79b931a5b809555f9cff01/compiler/src/compilers/cpp_compiler.rs#L45

**Comment by virtustron** [comment]
Test compilation of the simple file 

`g++ -o test test.cpp >stdout_file`

returns empty stdout

**Comment by virtustron** [comment]
Actually this issue is not completely a bug - because [compiler option "-o"](https://gcc.gnu.org/onlinedocs/gcc-3.1.1/gcc/Overall-Options.html#Overall%20Options) we used line 38  (with binary file name next to it) is this stdout itself.  

https://github.com/ITA-Dnipro/CompilerWebApp/blob/212eeba30b3f489ecd79b931a5b809555f9cff01/compiler/src/compilers/cpp_compiler.rs#L37-L41

So, we have such options as:
 - remove stdout field from OutpurData struct - it actually duplicates compiled_file_name field
 - push to stdout fome kind of log strings (for instance, "compilation begins...", "compilation succeded/failed...")
 
https://github.com/ITA-Dnipro/CompilerWebApp/blob/212eeba30b3f489ecd79b931a5b809555f9cff01/compiler/src/data/output_data/mod.rs#L7-L12

@ValentynFk, @AndriiSerbeniuk, @AlexanderSatana 
What do you think about this?

**Comment by valentynfaychuk** [comment]
I think as an option we can omit stdout member in JSON when sending responses to the client if stdout is empty (just in case if we will need stdout later on - we will have it ready)

**Comment by virtustron** [comment]
> if stdout is empty (just in case if we will need stdout later on - we will have it ready)

I made some changes to stdout filling - added information about compilation process (like in Visual Studio):
https://github.com/ITA-Dnipro/CompilerWebApp/blob/693433b7e30711824959d5dc54da7d891ae33e04/compiler/src/compilers/cpp_compiler.rs#L38

https://github.com/ITA-Dnipro/CompilerWebApp/blob/693433b7e30711824959d5dc54da7d891ae33e04/compiler/src/compilers/cpp_compiler.rs#L42

https://github.com/ITA-Dnipro/CompilerWebApp/blob/693433b7e30711824959d5dc54da7d891ae33e04/compiler/src/compilers/cpp_compiler.rs#L58
