### ISSUE TITLE
Make proper Compiler architecture

### ISSUE THREAD

**Issue by virtustron** [ITA-Dnipro/CompilerWebApp#5]
**Data** module with submodules:

**_Input data_** (under consideration)
 -  #Header (programming language),
 - Compiling options
 - Source code (path to file)

**_Output data_** (under consideration):
- Header
- Result of compilation;
- Compiled file (path to file)

**Handler** module  - provide main compilation process

**Compilers** module with submodules - call proper compiler and read compiler results:
- cpp_compiler
- rust_compiler
- ...

**Storage** module - provide operations with files and directories

**Comment by AndriiSerbeniuk** [comment]
About this one: 
> **_Input data_** (under consideration)
> * Source code (path to file)

Source code will be passed as a string, so don't bother with reading files.

Other than that I personally would be happy to hear more about output data, what will be returned in the case of compilation errors etc.
